### ISSUE TITLE
ERROR: No module named 'ayon_equalizer.version'

### ISSUE THREAD

**Issue by johhnry** [ynput/ayon-equalizer#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

I am launching the `ayon-launcher` from the console:

```
❯ .\build\output\ayon_console.exe --verbose debug
```

```
*** WRN: >>> { AddonsLoader }: [  FAILED to import "ayon_equalizer"  ]
==============================
No module named 'ayon_equalizer.version'
==============================
Traceback (most recent call last):
  File "C:\Users\joseph.henry\AppData\Local\Ynput\AYON\addons\core_1.0.0\ayon_core\addon\base.py", line 338, in _load_ayon_addons
    mod = __import__(basename, fromlist=("",))
  File "C:\Users\joseph.henry\AppData\Local\Ynput\AYON\addons\equalizer_0.1.0\ayon_equalizer\__init__.py", line 1, in <module>
    from .addon import EqualizerAddon, EQUALIZER_HOST_DIR
  File "C:\Users\joseph.henry\AppData\Local\Ynput\AYON\addons\equalizer_0.1.0\ayon_equalizer\addon.py", line 3, in <module>
    from .version import __version__
ModuleNotFoundERROR: No module named 'ayon_equalizer.version'
*** WRN: >>> { AddonsLoader }: [  Addon equalizer 0.1.0 has no content to import  ]
```

### Expected Behavior:

There should be a file named `version.py` like the [Photoshop integration](https://github.com/ynput/ayon-photoshop/blob/develop/client/ayon_photoshop/version.py) declaring the addon version.

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

1. `git clone https://github.com/ynput/ayon-equalizer`
2. `cd ayon-equalizer`
3. `python create_package.py`
4. Install the .zip in the addons in AYON web UI
5. Add the addon in the production bundle
6. Launch the launcher

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

**Comment by BigRoy** [comment]
Should be solved with https://github.com/ynput/ayon-equalizer/pull/5

**Comment by johhnry** [comment]
@BigRoy I was just looking at that, perfect!

**Comment by BigRoy** [comment]
If you're able to test it - would be great if you can confirm it does solve it for you. ❤️

**Comment by johhnry** [comment]
@BigRoy I don't have any license right now so I can't test but I will on `develop` if I have one, thanks!
